#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --mem=64G
#SBATCH --output=geno_raw.out
#SBATCH --job-name=geno_raw

/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_16_stor_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/acidity_16_stor_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_16_stor_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/brix_16_stor_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_16_stor_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/weight_avg_16_stor_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_16_stor_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/firmness_avg_16_stor_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_16_stor_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/brix_acid_16_stor_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_16_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/acidity_16_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/juiciness_16_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/juiciness_16_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/date_jul_16_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/date_jul_16_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_16_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/weight_avg_16_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_avg_16_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/brix_avg_16_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_16_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/firmness_avg_16_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/flowering_jul_16_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/flowering_jul_16_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/precocity_16_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/precocity_16_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_16_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/brix_acid_16_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/time_ripen_16_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/time_ripen_16_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_acidity_16_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/percent_acidity_16_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_16_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/percent_brix_16_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_weight_16_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/percent_weight_16_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_firmness_avg_16_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/percent_firmness_avg_16_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_acid_16_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/percent_brix_acid_16_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_17_stor_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/acidity_17_stor_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_17_stor_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/brix_17_stor_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_17_stor_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/weight_avg_17_stor_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_17_stor_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/firmness_avg_17_stor_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_17_stor_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/brix_acid_17_stor_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_17_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/brix_17_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_17_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/acidity_17_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/date_jul_17_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/date_jul_17_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_17_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/firmness_avg_17_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_17_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/weight_avg_17_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_17_harv_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/brix_acid_17_harv_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_acidity_17_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/percent_acidity_17_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_17_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/percent_brix_17_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_weight_avg_17_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/percent_weight_avg_17_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_firmness_avg_17_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/percent_firmness_avg_17_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_acid_17_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/percent_brix_acid_17_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/tpc_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/tpc_geno_filtered --recode A
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/time_ripen_2017_geno_filtered --out /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/geno_raw/time_ripen_2017_geno_filtered --recode A
