#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --mem=64G
#SBATCH --output=kinship.out
#SBATCH --job-name=kinship

module load java

/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_16_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_16_stor_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/acidity_16_stor_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_16_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_16_stor_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/brix_16_stor_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_16_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_16_stor_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/weight_avg_16_stor_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_16_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_16_stor_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/firmness_avg_16_stor_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_16_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_16_stor_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/brix_acid_16_stor_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_16_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/acidity_16_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/juiciness_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/juiciness_16_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/juiciness_16_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/date_jul_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/date_jul_16_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/date_jul_16_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_16_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/weight_avg_16_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_avg_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_avg_16_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/brix_avg_16_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_16_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/firmness_avg_16_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/flowering_jul_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/flowering_jul_16_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/flowering_jul_16_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/precocity_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/precocity_16_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/precocity_16_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_16_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/brix_acid_16_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/time_ripen_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/time_ripen_16_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/time_ripen_16_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_acidity_16_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_acidity_16_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/percent_acidity_16_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_16_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_16_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/percent_brix_16_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_weight_16_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_weight_16_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/percent_weight_16_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_firmness_avg_16_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_firmness_avg_16_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/percent_firmness_avg_16_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_acid_16_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_acid_16_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/percent_brix_acid_16_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_17_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_17_stor_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/acidity_17_stor_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_17_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_17_stor_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/brix_17_stor_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_17_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_17_stor_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/weight_avg_17_stor_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_17_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_17_stor_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/firmness_avg_17_stor_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_17_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_17_stor_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/brix_acid_17_stor_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_17_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/brix_17_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_17_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/acidity_17_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/date_jul_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/date_jul_17_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/date_jul_17_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_17_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/firmness_avg_17_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_17_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/weight_avg_17_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_17_harv_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/brix_acid_17_harv_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_acidity_17_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_acidity_17_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/percent_acidity_17_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_17_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_17_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/percent_brix_17_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_weight_avg_17_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_weight_avg_17_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/percent_weight_avg_17_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_firmness_avg_17_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_firmness_avg_17_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/percent_firmness_avg_17_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_acid_17_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_acid_17_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/percent_brix_acid_17_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/tpc_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/tpc_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/tpc_kinship.txt -exportType SqrMatrix
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/time_ripen_2017_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/time_ripen_2017_geno_filtered.map -KinshipPlugin -method Centered_IBS -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/kinship/time_ripen_2017_kinship.txt -exportType SqrMatrix
