#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --mem=64G
#SBATCH --output=pca.out
#SBATCH --job-name=pca

module load java

/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_16_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_16_stor_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/acidity_16_stor_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_16_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_16_stor_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/brix_16_stor_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_16_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_16_stor_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/weight_avg_16_stor_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_16_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_16_stor_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/firmness_avg_16_stor_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_16_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_16_stor_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/brix_acid_16_stor_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_16_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/acidity_16_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/juiciness_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/juiciness_16_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/juiciness_16_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/date_jul_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/date_jul_16_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/date_jul_16_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_16_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/weight_avg_16_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_avg_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_avg_16_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/brix_avg_16_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_16_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/firmness_avg_16_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/flowering_jul_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/flowering_jul_16_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/flowering_jul_16_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/precocity_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/precocity_16_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/precocity_16_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_16_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/brix_acid_16_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/time_ripen_16_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/time_ripen_16_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/time_ripen_16_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_acidity_16_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_acidity_16_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/percent_acidity_16_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_16_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_16_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/percent_brix_16_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_weight_16_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_weight_16_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/percent_weight_16_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_firmness_avg_16_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_firmness_avg_16_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/percent_firmness_avg_16_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_acid_16_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_acid_16_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/percent_brix_acid_16_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_17_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_17_stor_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/acidity_17_stor_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_17_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_17_stor_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/brix_17_stor_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_17_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_17_stor_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/weight_avg_17_stor_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_17_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_17_stor_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/firmness_avg_17_stor_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_17_stor_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_17_stor_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/brix_acid_17_stor_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_17_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/brix_17_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/acidity_17_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/acidity_17_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/date_jul_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/date_jul_17_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/date_jul_17_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/firmness_avg_17_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/firmness_avg_17_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/weight_avg_17_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/weight_avg_17_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_17_harv_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/brix_acid_17_harv_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/brix_acid_17_harv_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_acidity_17_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_acidity_17_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/percent_acidity_17_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_17_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_17_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/percent_brix_17_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_weight_avg_17_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_weight_avg_17_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/percent_weight_avg_17_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_firmness_avg_17_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_firmness_avg_17_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/percent_firmness_avg_17_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_acid_17_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/percent_brix_acid_17_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/percent_brix_acid_17_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/tpc_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/tpc_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/tpc_pca_ -runfork1
/project/6003429/myles_lab/bin/tassel5/tasseladmin-tassel-5-standalone-68140c7ab0dc/run_pipeline.pl -Xms512m -Xmx10g -fork1 -plink -ped /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/time_ripen_2017_geno_filtered.ped -map /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/genotype_data/time_ripen_2017_geno_filtered.map -PrincipalComponentsPlugin -covariance true -endPlugin -export /project/6003429/myles_lab/abc_gwas/big_gwas_analysis/gwas/pca/time_ripen_2017_pca_ -runfork1
