---
title: "PCA and LD decay"
author: "Sophie Watts"
date: '2021-05-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = F, warning = F)

library(viridis)
library(tidyverse)
library(patchwork)

```

```{r tassel_pca}
#remove unanchored SNPs
snps <- read_table2("../data/abc_combined_maf001_sort_vineland_imputed_pheno_hetero90_maf001.frq")
snps <- snps %>% filter(CHR == 0) %>% select(SNP)
#save file to be excluded using PLINK
write.table(snps, "outputs/contig_snps_remove.txt", sep = "\t", row.names = F, col.names = F, quote = F)

/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file /project/6003429/myles_lab/abc_gwas/genotype_filtering/abc_combined_maf001_sort_vineland_imputed_pheno_hetero90_maf001 --exclude contig_snps_remove.txt --out abc_combined_maf001_sort_vineland_imputed_pheno_hetero90_maf001_noctgs --recode

#252642 SNPs remain.

#LD prune -indep-pairwise 10 3 0.5
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file abc_combined_maf001_sort_vineland_imputed_pheno_hetero90_maf001_noctgs -indep-pairwise 10 3 0.5 --out abc_combined_maf001_sort_vineland_imputed_pheno_hetero90_maf001_noctgs

#remove 87,650 SNPs
/project/6003429/myles_lab/bin/plink_linux_x86_64/plink --file abc_combined_maf001_sort_vineland_imputed_pheno_hetero90_maf001_noctgs --exclude abc_combined_maf001_sort_vineland_imputed_pheno_hetero90_maf001_noctgs.prune.out --out abc_combined_maf001_sort_vineland_imputed_pheno_hetero90_maf001_noctgs_pruned --recode
#164992 SNPs remain

#run pca with TASSEL script

```

#Principal components analysis.

```{r pca}
#See ../shell_scripts/abc_pca.sh for the commands used to run PCA with TASSEL.

#load tassel pca output
abc_pcs <- read_table2("../data/abc_combined_maf001_sort_vineland_imputed_pheno_hetero90_maf001_noctgs_pruned1.txt", 
    skip = 2)
pheno_data <- read_csv("../outputs/geno_pheno_meta_data.csv")

pcs_pheno <- left_join(abc_pcs, pheno_data, by = c("Taxa"="apple_id"))

#Set sylvestris and hybrid accessions to NA (this will add to the 3 accessions that are already NA for species).
pcs_pheno <- pcs_pheno %>% mutate(species = na_if(species, "hybrid"))
pcs_pheno <- pcs_pheno %>% mutate(species = na_if(species, "sylvestris"))

#Make NAs a value
pcs_pheno <- pcs_pheno %>% mutate(species = replace_na(species, "NA"))

#make species factors
pcs_pheno$species <- as.factor(pcs_pheno$species)
#reorder levels
pcs_pheno$species <- factor(pcs_pheno$species, levels = c("domestica", "sieversii", "NA"))


#Load eigen results.
eigen <- read_delim("../data/abc_combined_maf001_sort_vineland_imputed_pheno_hetero90_maf001_noctgs_pruned2.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)

eigen <- eigen %>%  mutate(per_var = `proportion of total`*100)
eigen <- eigen %>% filter(PC < 10) %>% mutate(PC = PC +1)

#remove rows that are NA for harvest date
harv_na <- pcs_pheno %>% filter(is.na(date_jul_17_harv)) %>% select(Taxa, PC1, PC2, date_jul_17_harv, species)

harv <- pcs_pheno %>% filter(!is.na(date_jul_17_harv)) %>% select(Taxa, PC1, PC2, date_jul_17_harv, species)

data <- rbind(harv_na, harv)

pca_species <- ggplot(data, aes(x=PC1, y=PC2))+
  geom_point(aes(shape=species, colour=date_jul_17_harv),size=3, stroke=0, alpha=0.8)+
  theme_bw()+
  coord_fixed()+
  scale_color_viridis(name = "Harvest date (days)", option = "magma", direction = -1)+
  scale_shape_discrete(name = "Species", labels = c("M. domestica", "M. sieversii"))+
  labs(x=paste0("PC1 (5.5%)"), y=paste0("PC2 (3.1%)"))+
  theme(panel.border = element_blank(), axis.text=element_text(colour = "black", size=10), axis.title=element_text(size = 10, face = "bold"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), plot.title = element_text(size = 9))
ggsave("../figures/pca_species.pdf", plot = pca_species)

```

#Correlate PCs with phenotypes.

```{r pheno_pc_correlations}

#remove sylvestris and hybrid (this will also remove 3 accessions that are NA for species)
#pcs_pheno <- pcs_pheno %>% mutate(bin_species = species)

#Make species, use and world phenotype binary.
pcs_pheno <- pcs_pheno %>%
  mutate(bin_species = case_when(
  species == "sieversii"  ~ 0,
  species == "domestica"  ~ 1))

#make wild, crab and rootstock accession NA.

pcs_pheno <- pcs_pheno %>%
  mutate(bin_use = case_when(
  use == "cider"  ~ 0,
  use == "dessert"  ~ 1))

pcs_pheno <- pcs_pheno %>%
  mutate(bin_world = case_when(
  world == "old"  ~ 0,
  world == "new"  ~ 1))

#Correlate PC1 with phenotypes
#we only want phenotypes from 2017 (pheno_list_2017.txt)

pheno_cor_pc1 <- pcs_pheno %>% select(PC1, juiciness_16_harv, flowering_jul_16_harv, precocity_16_harv, acidity_17_stor, brix_17_stor, weight_avg_17_stor, firmness_avg_17_stor, brix_acid_17_stor, brix_17_harv, acidity_17_harv, date_jul_17_harv, firmness_avg_17_harv, weight_avg_17_harv, brix_acid_17_harv, percent_acidity_17, percent_brix_17, percent_weight_avg_17, percent_firmness_avg_17, percent_brix_acid_17, tpc, time_ripen_2017, bin_species, bin_world, bin_use) %>% mutate_all(as.numeric)

pheno_cor_pc1 <- as.matrix(pheno_cor_pc1)

r2 = p = c()
for (i in 2:ncol(pheno_cor_pc1)) {
  year_correlation <- cor.test(pheno_cor_pc1[,1], pheno_cor_pc1[,i], method = "pearson")
  r2[i] = year_correlation$estimate^2
  p[i] = year_correlation$p.val
}
cor_p = p * 43 #43 comparisons to multiple test correct for.
pc1_vs_phenos = cbind(colnames(pheno_cor_pc1), r2, cor_p)
pc1_vs_phenos = pc1_vs_phenos[-1,]
pc1_vs_phenos <- as.data.frame(pc1_vs_phenos)
pc1_vs_phenos$cor_p <- as.numeric(as.character(pc1_vs_phenos$cor_p))
pc1_vs_phenos$r2 <- as.numeric(as.character(pc1_vs_phenos$r2))
pc1_vs_phenos$r2 <- signif(pc1_vs_phenos$r2, 3)
pc1_vs_phenos <- pc1_vs_phenos %>% arrange(desc(r2))

pc1_vs_phenos <- pc1_vs_phenos %>% rename(trait = V1)

write.csv(pc1_vs_phenos,file = "../outputs/new_pc1_vs_phenos.csv", quote = F, row.names = F)

#Correlate PC2 with phenotypes

pheno_cor_pc2 <- pcs_pheno %>% select(PC2, juiciness_16_harv, flowering_jul_16_harv, precocity_16_harv, acidity_17_stor, brix_17_stor, weight_avg_17_stor, firmness_avg_17_stor, brix_acid_17_stor, brix_17_harv, acidity_17_harv, date_jul_17_harv, firmness_avg_17_harv, weight_avg_17_harv, brix_acid_17_harv, percent_acidity_17, percent_brix_17, percent_weight_avg_17, percent_firmness_avg_17, percent_brix_acid_17, tpc, time_ripen_2017, bin_species, bin_world, bin_use) %>% mutate_all(as.numeric)

pheno_cor_pc2 <- as.matrix(pheno_cor_pc2)

r2 = p = c()
for (i in 2:ncol(pheno_cor_pc2)) {
  year_correlation <- cor.test(pheno_cor_pc2[,1], pheno_cor_pc2[,i], method = "pearson")
  r2[i] = year_correlation$estimate^2
  p[i] = year_correlation$p.val
}
cor_p = p * 43 #43 comparisons to multiple test correct for.
pc2_vs_phenos = cbind(colnames(pheno_cor_pc2), r2, cor_p)
pc2_vs_phenos = pc2_vs_phenos[-1,]
pc2_vs_phenos <- as.data.frame(pc2_vs_phenos)
pc2_vs_phenos$cor_p <- as.numeric(as.character(pc2_vs_phenos$cor_p))
pc2_vs_phenos$r2 <- as.numeric(as.character(pc2_vs_phenos$r2))
pc2_vs_phenos$r2 <- signif(pc2_vs_phenos$r2, 3)
pc2_vs_phenos <- pc2_vs_phenos %>% arrange(desc(r2))

write.csv(pc2_vs_phenos,file = "../outputs/pc2_vs_phenos.csv", quote = F, row.names = F)


```

#Correlation plot of harvest date with PC2.

```{r}

harvest_date_pc2 <- ggplot(data, aes(x=date_jul_17_harv, y=PC2))+
  geom_point(aes(colour=date_jul_17_harv),size=1, alpha=0.8)+
  theme_bw()+
  coord_fixed()+
  scale_color_viridis(option = "magma", direction = -1)+
  labs(x="Harvest date (days)", y="PC 2")+
  theme(legend.position = "none", panel.border = element_blank(), axis.text=element_text(colour = "black", size=10), axis.title=element_text(size = 10, face = "bold"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), plot.title = element_text(size = 9))+
  stat_smooth(method="lm", col="black", se = FALSE)+
  ggtitle(paste("r2 = ", signif(cor.test(pcs_pheno$date_jul_17_harv, pcs_pheno$PC2, method = "pearson")$estimate^2, digits = 3), " p-value = ", signif(cor.test(pcs_pheno$date_jul_17_harv, pcs_pheno$PC2, method = "pearson")$p.value, digits = 2))) 
ggsave("../figures/harvest_date_pc2.pdf", plot = harvest_date_pc2)

```

#Make boxplot of PC1 across domestica and sieversii.

```{r}

#Filter to only include sieversii and domestica
species_compare <- pcs_pheno %>% filter(species == "sieversii" | species == "domestica") %>% select(PC1, species)

species_compare$species <- as.factor(species_compare$species)

domestica <- species_compare %>% filter(species == "domestica")

sieversii <- species_compare %>% filter(species == "sieversii")

species_pc1_boxplot <- ggplot(species_compare, aes(x=species, y=PC1)) + 
  geom_boxplot()+
  theme_bw()+
  labs(x="Species", y="PC 1")+
  theme(panel.border = element_blank(), axis.text=element_text(colour = "black", size=10), axis.title=element_text(size = 10, face = "bold"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), plot.title = element_text(size = 9))+
  ggtitle(paste0("W= ",wilcox.test(domestica$PC1, sieversii$PC1, alternative = "two.sided")$statistic," p-value= ",wilcox.test(domestica$PC1, sieversii$PC1, alternative = "two.sided")$p.value))

ggsave("../figures/species_pc1_boxplot.pdf", plot = species_pc1_boxplot)


#Make full figure.

figure_1 <- pca_species/(species_pc1_boxplot | harvest_date_pc2) + plot_annotation(tag_levels = 'A')

ggsave("../figures/figure_1.pdf", plot = figure_1, width = 10, height = 10)

`
```

